# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reward Reports for Reinforcement Learning
# subtitle: 
email: geese-org@lists.berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  Website for the Reward Reports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rewardreports.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
logo: assets/img/rewardreports2.png
repository: RewardRewards/RewardReports.github.io

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Example of template variables:
# https://github.com/pages-themes/minimal/blob/master/_layouts/default.html

# Our tempalte is based on: https://github.com/baicsworkshop/baicsworkshop.github.io by Jessica Hamrick

# Example workshop sites that are nice:
# https://offline-rl-neurips.github.io/index.html
# https://tda-in-ml.github.io/
# https://kr2ml.github.io/2020/
# https://inductive-biases.github.io/#abstract
# https://dynamicdecisions.github.io/
# https://sslneuips20.github.io/index.html
# https://www.hadr.ai/home
# https://capworkshop.github.io/
#